import { Operator, TypingDirection, type MathForKids } from "./Types";

export const config: MathForKids.BasicMathSettings[] = [
	{
		name: 'Very basic',
		excercises: 10,
		firstOperandRangeMin: 1,
		firstOperandRangeMax: 9,
		secondOperandRangeMin: 2,
		secondOperandRangeMax: 5,
		operators: [Operator.PLUS],
		direction: TypingDirection.RtoL,
		showTime: false,
		automaticStepForward: true,
	},
	{
		name: 'Basic',
		excercises: 10,
		firstOperandRangeMin: 1,
		firstOperandRangeMax: 9,
		secondOperandRangeMin: 1,
		secondOperandRangeMax: 9,
		operators: [Operator.PLUS],
		direction: TypingDirection.RtoL,
		showTime: true,
		automaticStepForward: false,
	},
	{
		name: 'Intermediate',
		excercises: 10,
		firstOperandRangeMin: 11,
		firstOperandRangeMax: 99,
		secondOperandRangeMin: 1,
		secondOperandRangeMax: 99,
		operators: [Operator.PLUS],
		direction: TypingDirection.RtoL,
		showTime: true,
		automaticStepForward: false,
	},
	{
		name: 'Intermediate',
		excercises: 10,
		firstOperandRangeMin: 11,
		firstOperandRangeMax: 99,
		secondOperandRangeMin: 1,
		secondOperandRangeMax: 99,
		operators: [Operator.PLUS, Operator.MINUS],
		direction: TypingDirection.RtoL,
		showTime: true,
		automaticStepForward: true,
	}
]